### ISSUE TITLE
Code Review - Round 1

### ISSUE THREAD

**Issue by rfazeli** [kevinmfreire/sentiment-analysis#1]
### Overview
Great work so far, especially the explanations you have in your `tweet_dataset_analysis.ipynb` notebook are very helpful. Generally, adding explanations for each section in a notebook makes it very easy to follow and shows your theory knowledge. It will also be very easy to gather these notes later and turn them into an article (if we wanted to write about this project and publish it)

### Feedback
1. I know you have the links to the datasets that you use in the README but it might be a good idea to automate that process and set up a script that would automatically download the Kaggle datasets and place them in appropriate folders. This [article](https://www.endtoend.ai/tutorial/how-to-download-kaggle-datasets-on-ubuntu/) shows how you can use the Kaggle command-line tool to download datasets. If it's a non-Kaggle dataset then you can put the data in your Google Drive and add a link to it with a little script for downloading the data from its source. If the data is only a few MB then you can push it directly to your repo.
3. You should put all your data in a `data/` folder and your notebooks in a `notebooks/` folder. Also, add your scripts in a `src/` folder.
4. You already have functions from your notebook that you have refactored into Python scripts which is great. Just make sure you import those functions in your notebook rather than copy-pasting the function definition in your notebook.
5. Can you save .py versions of your notebooks as well and push both the .ipynb file and its corresponding .py file. This will help me reference specific sections of the code when reviewing it and it generally helps us easily compare different versions of your notebooks. There is some explanation [here](https://stackoverflow.com/questions/69322473/automatically-maintain-a-copy-of-a-jupyter-notebook-as-plain-python-code) that shows how to automate this process (but this is only for local jupyter notebooks not google colab ones)
6. Make sure you use a virtual environment and create a requirements.txt file for your project. This way anyone can easily clone your repository, recreate your environment and run your code.

So your folder structure would look like this:
```bash
├── data
│   ├── processed
│   │   ├── ...
│   └── raw
│   │   ├── ...
├── notebooks
│   ├── tweet_dataset_analysis.ipynb
│   ├── ...
├── src
│   ├── main.py
│   ├── pre_process.py
│   ├── ...
├── .gitiginore
├── README.md
├── requirements.txt
```

I have some more comments on your scripts which would be easier to discuss on our call tomorrow.

### Questions
1. Your `measure.py` script seems to be empty. Is this something you're still working on?

**Comment by kevinmfreire** [comment]
Closing Code Review - Round 1 as it has been complete.
