### ISSUE TITLE
Code Review - Round 2

### ISSUE THREAD

**Issue by rfazeli** [kevinmfreire/sentiment-analysis#2]
This is excellent progress. I think v0 of this project is pretty much done, great work!

### Feedback
I think your notebook needs more cleaning up (e.g. importing the library directly from your scripts), but if you think you won't be using the notebook any time soon then it's fine we can leave it as-is for now.

I tried to clone your repo, install the packages in requirements.txt and run the app but I realized I don't have the nltk packages you've used, so below I've suggested adding step-by-step instructions for cloning the repo and running the app.

### Suggestions
1. Add a script in the main project directory called `nltk_setup.py` and within it download all necessary nltk packages. 
2. Add instructions in your README.md for others to set up this project on their machine e.g. 
```bash
git clone ... # clone the repo
virtualenv .venv # create a virtual environment
source .venv/bin/activate # activate your virtual environment
pip install -r requirements.txt # install dependencies
python nltk_setup.py, etc. # install nltk packages
etc.
```
3. You could save your processed data as csv especially since you're input is csv as well. The pickle format is usually used for saving models.
https://github.com/kevinmfreire/sentiment-analysis/blob/625e7dae0824b0b90ac53d3744eba0f4630588a0/src/pre_process.py#L100
4. This function is called `tokenize_data()` but it's not tokenizing the text. It creates features and labels. You might want to rename this function 
https://github.com/kevinmfreire/sentiment-analysis/blob/625e7dae0824b0b90ac53d3744eba0f4630588a0/src/pre_process.py#L104
5. It'd be to clean up some of the commented code in the scripts and some of the imports you're not using anymore e.g.
https://github.com/kevinmfreire/sentiment-analysis/blob/625e7dae0824b0b90ac53d3744eba0f4630588a0/src/train.py#L6-L8
unless you're looking to use those models.
6. I think you can move the `load_data()` `train_test_data()` functions to another script called `utils.py` since they're not really evaluation functions.
https://github.com/kevinmfreire/sentiment-analysis/blob/625e7dae0824b0b90ac53d3744eba0f4630588a0/src/evaluate.py#L46-L60

**Comment by kevinmfreire** [comment]
All items have been addressed.
